alias clr="clear"
alias clear="screenfetch > .sf;clear;cat .sf"
alias python="python2"
alias shutdown="shutdown now"
alias vi="vim"
alias vibash="vim ~/.bashrc"
alias pacman="sudo pacman"
alias vi3="vim ~/.config/i3/config"
alias vii3="vi3"
alias mount="sudo mount"
alias umount="sudo umount"
alias unmount="umount"
alias sysd="systemctl"
alias re="sudo !!"
alias x="startx"
alias vilock="vim ~/scripts/lock.sh"
rm -rf Desktop
screenfetch
