alias clr="clear"
alias clear="clear; motd"
alias python="python2"
alias shutdown="shutdown now"
alias vi="vim"
alias vibash="vim ~/.bashrc"
alias pacman="sudo pacman"
alias vi3="vim ~/.config/i3/config"
alias vii3="vi3"
alias mount="sudo mount"
alias umount="sudo umount"
alias unmount="umount"
alias sysd="systemctl"
alias re="sudo !!"
alias x="startx"
alias vilock="vim ~/scripts/lock.sh"
alias motd="~/scripts/motd.sh"
alias visetup="vim ~/scripts/setup.sh"
alias vimotd="vim ~/scripts/motd.sh"
rm -rf Desktop
~/scripts/motd.sh
