alias clr="clear"
alias clear="clear && screenfetch"
alias python="python2"
alias shutdown="shutdown now"
alias vi="vim"
alias vibash="vim ~/.bashrc"
alias pacman="sudo pacman"
alias vi3="vim ~/.config/i3/config"
alias vii3="vi3"
alias mount="sudo mount"
alias umount="sudo umount"
alias unmount="umount"
alias sysd="systemctl"
alias re="sudo !!"
alias x="startx"
rm -rf Desktop
screenfetch
